### BOOK
###
GET http://localhost:3000/books

###
GET http://localhost:3000/books/7

###
POST http://localhost:3000/books
Content-Type: application/json

{
  "isbn": "9785555551106",
  "title": "La Nueva Mente del Emperador",
  "editionNumber": "1st",
  "editionDate": "2015-12-10T00:00:00Z",
  "maxLoanDays": 25
}

###
PATCH http://localhost:3000/books/1
Content-Type: application/json

{
  "title": "Cien Años de Soledad",
  "editionDate": "2015-12-10T00:00:00Z"
}

###
DELETE http://localhost:3000/books/7



### COPY
###
GET http://localhost:3000/copies

###
GET http://localhost:3000/copies/7

###
POST http://localhost:3000/copies
Content-Type: application/json

{
  "bookId": 10
}

###
PATCH http://localhost:3000/copies
Content-Type: application/json

{
  "copyId": 16,
  "bookId": 9
}

###
DELETE http://localhost:3000/copies/7



### SANCTION POLICY
###
GET http://localhost:3000/sanctionPolicies

###
GET http://localhost:3000/sanctionPolicies/2

###
POST http://localhost:3000/sanctionPolicies
Content-Type: application/json

{
  "daysLateFrom": 61,
  "daysLateTo": 120,
  "sanctionDays": 90
}

###
PATCH http://localhost:3000/sanctionPolicies/5
Content-Type: application/json

{
  "daysLateTo": 60,
  "sanctionDays": 151510510
}

###
DELETE http://localhost:3000/sanctionPolicies/6



### LOAN POLICY
###
GET http://localhost:3000/loanPolicy

###
POST http://localhost:3000/loanPolicy
Content-Type: application/json

{
  "maxPendingBooks": 7
}



### SANCTION
###
GET http://localhost:3000/sanctions

###
GET http://localhost:3000/sanctions/5

<!-- TODO -> CREATE SANCTION
###
POST http://localhost:3000/sanctions
Content-Type: application/json
  
{
  "sanctionDate": "2025-06-01T00:00:00Z",
  "sanctionDays": 10
}
-->

###
PATCH http://localhost:3000/sanctions/5
Content-Type: application/json

{
  "sanctionDate": "2024-12-25T23:59:59Z",
  "sanctionDays": 2
}

###
DELETE http://localhost:3000/sanctions/5



### MEMBER
###
GET http://localhost:3000/members

###
GET http://localhost:3000/members/2

###
POST http://localhost:3000/members
Content-Type: application/json

{
  "firstName": "Tincho",
  "lastName": "Galva",
  "email": "martingalvano174@gmail.com",
  "address": "1336 Zeballos",
  "phone": "+54 341 3001515"
}

###
PATCH http://localhost:3000/members/9
Content-Type: application/json

{
  "memberStatus": "Enabled"
}

###
DELETE http://localhost:3000/members/9