###
GET http://localhost:3000/copies

###
GET http://localhost:3000/copies/7

###
POST http://localhost:3000/books
Content-Type: application/json

{
  "isbn": "9785555551106",
  "title": "La Nueva Mente del Emperador",
  "editionNumber": "1st",
  "editionDate": "2015-12-10T00:00:00Z",
  "maxLoanDays": 25
}

###
POST http://localhost:3000/copies
Content-Type: application/json

{
  "bookId": 11
}

###
PATCH http://localhost:3000/copies
Content-Type: application/json

{
  "copyId": 16,
  "bookId": 11
}

###
DELETE http://localhost:3000/copies/7
